### ISSUE TITLE
Expression 'android' cannot be invoked as a function. The function 'invoke()' is not found

### ISSUE THREAD

**Issue by nikospamp** [boguszpawlowski/AndroidTemplate#8]
On the application's gradle I am getting the following error. Its on 4.1.3 for Windows 64-bit.

Great template.

**Edit:** the issue seems to be happening when I update the `com.android.tools.build:gradle` from `4.0.1` to `7.0.0-alpha10`

![image](https://user-images.githubusercontent.com/10252329/113215483-9601bf00-9283-11eb-9e0c-a3dad9d7afb5.png)

**Comment by boguszpawlowski** [comment]
@nikospamp Thanks for the info. The repo was created with alpha version of gradle plugin, so it may not run properly on stable version of AndroidStudio. Will add info about it in Readme, as well as steps to revert to stable gradle plugin.

**Comment by nikospamp** [comment]
Downloading canary did the trick, you were right. Thanks mate!
